name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-cache-
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm i @nrwl/nx-linux-x64-gnu@^15
      - run: npx nx run functions:build
      - run: npm publish dist/packages/functions
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - run: npx nx run browser:build
      - run: npm publish dist/packages/browser
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
